name: Docker Image Publishing Blueprint

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: true
        type: string
      unit_tests_path:
        required: true
        type: string
      code_coverage_threshold:
        required: true
        type: number
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image_name }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and export Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          load: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Unit tests with code coverage
        run: |
          dotnet test ${{ inputs.unit_tests_path }} \
          --configuration Release \
          --verbosity minimal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage \
          --settings tests/Beter.TestingTools.Generator.UnitTests/coverlet.runsettings

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '0 80'
        
      - name: Install ReportGenerator tool
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate code coverage report in HTML
        run: reportgenerator -reports:./coverage/**/coverage.cobertura.xml -targetdir:./coverage/report/${{inputs.project_name}} -reporttypes:"Html"

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
