name: Docker Image CI Pipeline for Emulator and Generator

on:
  workflow_dispatch:
  push:
    tags: [ 'v[0-9]*.[0-9]*.[0-9]*' ]

jobs:
  integration-tests:
    name: Run Integration Tests 
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: Run Integration Tests
       run: |
          dotnet test tests/Beter.TestingTools.IntegrationTests --logger "console;verbosity=detailed"

  emulator_push_to_docker_hub:
    needs: integration-tests
    if: needs.integration-tests.result == 'success' 
    name: Emulator
    uses: oleksiygarnik/beter-testing-tools/.github/workflows/base-docker-publish.yml@main
    with:
      project_name: emulator
      image_name: docker.io/silencerdev/testingtools.emulator
      dockerfile_path: src/Hosts/Beter.TestingTools.Emulator
      unit_tests_path: tests/Beter.TestingTools.Emulator.UnitTests
      code_coverage_threshold: 75
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          
  generator_push_to_docker_hub:
    needs: integration-tests
    if: needs.integration-tests.result == 'success' 
    name: Generator
    uses: oleksiygarnik/beter-testing-tools/.github/workflows/base-docker-publish.yml@main
    with:
      project_name: generator
      image_name: docker.io/silencerdev/testingtools.generator
      dockerfile_path: src/Hosts/Beter.TestingTools.Generator
      unit_tests_path: tests/Beter.TestingTools.Generator.UnitTests
      code_coverage_threshold: 75
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
