name: Docker Image CI Pipeline for Emulator and Generator

on:
  workflow_dispatch:
  push:
    tags: [ 'v[0-9]*.[0-9]*.[0-9]*' ]

jobs:
  emulator_push_to_docker_hub:
    name: Emulator
    uses: oleksiygarnik/beter-testing-tools/.github/workflows/base-docker-publish.yml@main
    with:
      project_name: emulator
      image_name: docker.io/silencerdev/testingtools.emulator
      dockerfile_path: src/Hosts/Beter.Feed.TestingSandbox.Emulator
      unit_tests_path: tests/Beter.Feed.TestingSandbox.Emulator.UnitTests
      code_coverage_threshold: 75
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          
  generator_push_to_docker_hub:
    name: Generator
    uses: oleksiygarnik/beter-testing-tools/.github/workflows/base-docker-publish.yml@main
    with:
      project_name: generator
      image_name: docker.io/silencerdev/testingtools.generator
      dockerfile_path: src/Hosts/Beter.Feed.TestingSandbox.Generator
      unit_tests_path: tests/Beter.Feed.TestingSandbox.Generator.UnitTests
      code_coverage_threshold: 75
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
